export const treeBlog = [
  {
    id: 1,
    title: "Ficus Bonsai Tree",
    description:
      "A beautiful Ficus bonsai tree with dense foliage, perfect for home or office decoration.",
    price: 50.99,
    old_price: 65.99,
    stock: 44,
    rating: 4.7,
    offer: "20% Off",
    category: "Featured",
    isNewArrival: false,
    isTrending: true,
    popularity: 90,
    images: [
      { url: "https://i.ibb.co.com/PYGF760/1.webp" },
      { url: "https://i.ibb.co.com/2n2QxK2/1-300x300.webp" },
      { url: "https://i.ibb.co.com/c8gCTdc/2-300x300.webp" },
    ],
  },
  {
    id: 2,
    title: "Japanese Maple Bonsai",
    description:
      "A stunning Japanese Maple bonsai tree with vibrant red leaves.",
    price: 120.0,
    old_price: 150.0,
    stock: 93,
    rating: 4.8,
    offer: "Save $30",
    category: "Featured",
    isNewArrival: true,
    isTrending: true,
    popularity: 95,
    images: [
      { url: "https://i.ibb.co.com/ggxRX5W/3-300x300.webp" },
      { url: "https://i.ibb.co.com/yVGJZWG/4.webp" },
      { url: "https://i.ibb.co.com/QHkTSqd/5.webp" },
    ],
  },
  {
    id: 3,
    title: "Pine Bonsai Tree",
    description:
      "An evergreen Pine bonsai tree, symbolizing resilience and longevity.",
    price: 90.5,
    old_price: 110.0,
    stock: 19,
    rating: 4.5,
    offer: "18% Off",
    category: "Featured",
    isNewArrival: false,
    isTrending: true,
    popularity: 85,
    images: [
      { url: "https://i.ibb.co.com/gSXHKt3/6.webp" },
      { url: "https://i.ibb.co.com/LrzHQkz/7-300x300.webp" },
      { url: "https://i.ibb.co.com/mDThQqw/9-300x300.webp" },
    ],
  },
  {
    id: 4,
    title: "Mini Jade Plant",
    description:
      "A succulent bonsai tree with lush green leaves, easy to grow and care for.",
    price: 25.99,
    old_price: 30.0,
    stock: 17,
    rating: 4.6,
    offer: "15% Off",
    category: "Featured",
    isNewArrival: true,
    isTrending: false,
    popularity: 75,
    images: [
      { url: "https://i.ibb.co.com/vw3y5gm/10-300x300.webp" },
      { url: "https://i.ibb.co.com/vXHT2Zf/11.webp" },
      { url: "https://i.ibb.co.com/DrNZc2X/11-300x300.webp" },
    ],
  },
  {
    id: 5,
    title: "Cedar Bonsai Tree",
    description:
      "A majestic Cedar bonsai tree with intricate branches and needle-like foliage.",
    price: 75.0,
    old_price: 90.0,
    stock: 17,
    rating: 4.4,
    offer: "Save $15",
    category: "Bestselling",
    isNewArrival: false,
    isTrending: true,
    popularity: 88,
    images: [
      { url: "https://i.ibb.co.com/zWcNMQ3/12-300x300.webp" },
      { url: "https://i.ibb.co.com/vx2qHzn/13-300x300.webp" },
      { url: "https://i.ibb.co.com/G557JgJ/14-300x300.webp" },
    ],
  },
  {
    id: 6,
    title: "Cherry Blossom Bonsai",
    description:
      "A delicate Cherry Blossom bonsai tree with pink blooms, ideal for spring decor.",
    price: 140.0,
    old_price: 175.0,
    stock: 19,
    rating: 4.9,
    offer: "Save $35",
    category: "Bestselling",
    isNewArrival: true,
    isTrending: true,
    popularity: 98,
    images: [
      { url: "https://i.ibb.co.com/hCY7dqt/15.webp" },
      { url: "https://i.ibb.co.com/6P0rsp4/16.webp" },
      { url: "https://i.ibb.co.com/D1NPDHG/17.webp" },
    ],
  },
  {
    id: 7,
    title: "Juniper Bonsai Tree",
    description:
      "A robust Juniper bonsai tree known for its versatile styling potential.",
    price: 65.0,
    old_price: 80.0,
    stock: 13,
    rating: 4.5,
    offer: "18% Off",
    category: "Bestselling",
    isNewArrival: false,
    isTrending: true,
    popularity: 87,
    images: [
      { url: "https://i.ibb.co.com/gRJBG9n/18.webp" },
      { url: "https://i.ibb.co.com/k8jdshL/21.webp" },
      { url: "https://i.ibb.co.com/BVHLWY1/22.webp" },
    ],
  },
  {
    id: 8,
    title: "Olive Bonsai Tree",
    description:
      "A hardy Olive bonsai tree with small, silvery-green leaves and a unique bark texture.",
    price: 110.0,
    stock: 16,
    old_price: 135.0,
    rating: 4.6,
    offer: "Save $25",
    category: "Bestselling",
    isNewArrival: true,
    isTrending: false,
    popularity: 83,
    images: [
      { url: "https://i.ibb.co.com/X4DRh14/23.webp" },
      { url: "https://i.ibb.co.com/mBtdMHZ/24.webp" },
      { url: "https://i.ibb.co.com/BNRc5Xq/24-300x300.webp" },
    ],
  },
  {
    id: 9,
    title: "Azalea Bonsai",
    description:
      "A vibrant Azalea bonsai tree with colorful flowers, adding life to any space.",
    price: 85.0,
    old_price: 100.0,
    stock: 11,
    rating: 4.7,
    offer: "15% Off",
    category: "Latest",
    isNewArrival: true,
    isTrending: true,
    popularity: 92,
    images: [
      { url: "https://i.ibb.co.com/gjbkQBY/25.webp" },
      { url: "https://i.ibb.co.com/NYxWtft/25-300x300.webp" },
      { url: "https://i.ibb.co.com/7nqykyt/27.webp" },
    ],
  },
  {
    id: 10,
    title: "Boxwood Bonsai",
    description:
      "A Boxwood bonsai tree with dense, rounded foliage, perfect for beginners.",
    price: 45.0,
    old_price: 55.0,
    stock: 20,
    rating: 4.4,
    offer: "Save $10",
    category: "Latest",
    isNewArrival: false,
    isTrending: false,
    popularity: 78,
    images: [
      { url: "https://i.ibb.co.com/Nxtfqrx/28-300x300.webp" },
      { url: "https://i.ibb.co.com/9r6M7pV/29.webp" },
      { url: "https://i.ibb.co.com/YPTx7jq/29-300x300.webp" },
    ],
  },
  {
    id: 11,
    title: "Cypress Bonsai",
    description:
      "A Cypress bonsai tree with thin, elongated leaves and a serene appearance.",
    price: 70.0,
    old_price: 85.0,
    stock: 17,
    rating: 4.3,
    offer: "17% Off",
    category: "Latest",
    isNewArrival: true,
    isTrending: true,
    popularity: 80,
    images: [
      { url: "https://i.ibb.co.com/6X0WB9q/30.webp" },
      { url: "https://i.ibb.co.com/jZHP7N8/490x490.jpg" },
      { url: "https://i.ibb.co.com/vw3y5gm/10-300x300.webp" },
    ],
  },
  {
    id: 12,
    title: "Moss Bonsai Tree",
    stock: 13,
    description:
      "A unique bonsai tree covered with soft moss, ideal for minimalist decor.",
    price: 55.0,
    old_price: 65.0,
    rating: 4.2,
    offer: "15% Off",
    category: "Latest",
    isNewArrival: true,
    isTrending: false,
    popularity: 77,
    images: [
      { url: "https://i.ibb.co.com/zWcNMQ3/12-300x300.webp" },
      { url: "https://i.ibb.co.com/mDThQqw/9-300x300.webp" },
      { url: "https://i.ibb.co.com/2n2QxK2/1-300x300.webp" },
    ],
  },
];
